# example netlify.toml
[build]
  command = "npm install . && npm run build"
  publish = ""
[dev]
  functions = "api"
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@sparticuz/chromium"]